server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:payment-service}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-payment}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  
  liquibase:
    change-log: ${CHANGE_LOG:classpath:db/changelog/db.changelog-master.xml}
    enabled: ${LIQUIBASE_ENABLED:true}

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.graduationproject.payment_service: ${LOG_LEVEL_APP:DEBUG}
    liquibase: ${LOG_LEVEL_LIQUIBASE:DEBUG}
    org.springframework.jdbc.core: ${LOG_LEVEL_JDBC:TRACE}
    